#!/bin/bash
#
# jargmised arvud tehakse labi arvudega 1-20 ukshaaval
for (( arv=1; arv<21; arv++ ))
do
# kontrollime
	if [ $arv -eq 0 -o $arv -eq 1]; then
		echo "$arv - ei ole algarv"
	else
		jagaja=2
		jaak=$(($arv % $jagaja))
		while [ $jaak -ne 0 ]
		do
			jagaja=$(($jagaja + 1))
			jaak=$(($arv % $jagaja))
		done
		if [ $arv -eq $jagaja ]; then
			echo "$arv - on algarv"
		else
			echo "$arv - ei ole algarv"
		fi
	fi
done
# lopp
